[package]
name = "aggreg"
version = "0.8.0"
authors = ["Guillaume Richard <mynameiskaneel@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
clap = "2.33.0"
futures = "0.3"
isahc = "0.8.2"
scraper = "0.11.0"
serde_json = "1.0"
serde = { version="1.0.104", features = ["derive"] }
